### ISSUE TITLE
Doesn't seem to work with iOS 13

### ISSUE THREAD

**Issue by thomas-alrek** [toddbluhm/cordova-plugin-launchscreen-storyboard#5]
On iOS 13 `window.LaunchScreen` is `undefined`.

This makes it impossible to call the `LaunchScreen.hide()` method.

The effect is that the CDVLaunchScreen is shown, but then suddenly dissapears. Then there are a few seconds of a white blank screen before the initial web content is shown.

**Comment by toddbluhm** [comment]
Hey @thomas-alrek 

I actually do not even use cordova anymore. This was for a project I was working on nearly 3 years ago and haven't touched cordova since then. If you want to PR a fix for this, I will certainly accept one, but I will not be fixing this issue. I am too far removed from this code and cordova/ios in general to fix this issue. I am surprised there is not an official/better solution from cordova yet for something like this! This project will probably just die off as pre-iOS 13 devices evaporate.

I apologize for the inconvenience and I am glad you got some use out of this plugin. I suppose if enough people come asking, then I might reconsider, but I am not anticipating that.

**Comment by akadebnath** [comment]
> Hey @thomas-alrek
> 
> I actually do not even use cordova anymore. This was for a project I was working on nearly 3 years ago and haven't touched cordova since then. If you want to PR a fix for this, I will certainly accept one, but I will not be fixing this issue. I am too far removed from this code and cordova/ios in general to fix this issue. I am surprised there is not an official/better solution from cordova yet for something like this! This project will probably just die off as pre-iOS 13 devices evaporate.
> 
> I apologize for the inconvenience and I am glad you got some use out of this plugin. I suppose if enough people come asking, then I might reconsider, but I am not anticipating that.

Cordova itself is dying. There is a big issue that iOS will stop accepting apps that refers to UI Webview. Cordova is based on UI Webview, and now there is hardly anyone working fulltime on Cordova. Hence, no one knows when or whether Cordova will update its engine to WK Webview. There are surely plugins to use WK Webview, but iOS seems to be intolerant to any UI Webview reference. If no one fixes the issue, it will be end of Cordova. Lots of apps and app developers will be wiped out if they don't migrate to native.

Now coming back to this particular plugin, there is hardly any alternative. iOS has already deprecated UILaunchImages. They are intimidating developers to use storyboard. Hence, there is serious requirement for this plugin to work. I can see there will be demand of this one soon. 

I can understand it may be difficult to find time for working on something you are no longer using. But some people (including me) won't mind hitting a PayPal Donation button for the help.

**Comment by vesper8** [comment]
Just received an email from Apple just now stating that as of June 30th 2020 using an Xcode storyboard will become a requirement. This has me a little worried since I don't yet use one. I then found this plugin and became even more worried as it's the most recently updated plugin on Github that matches the keywords "Cordova Storyboard" and.. apparently it doesn't work anymore.

But then I found this alternative plugin which seems to support it and is actively maintained: https://github.com/apache/cordova-plugin-splashscreen

**Comment by toddbluhm** [comment]
@vesper8 does https://github.com/apache/cordova-plugin-splashscreen replace/replicate all functionality of this repo? If so, I am happy to put a deprecation noticed on this repo and point everyone to that repo. It seems that like that one is the official Cordova plugin anyways?

**Comment by akadebnath** [comment]
cordova-plugin-splashscreen is the official plugin as it is from Apache itself. It has Storyboard feature for long time. I just tried it and the single-image Storyboard is working fine.

**Comment by vesper8** [comment]
@toddbluhm I don't know as I've never used this one before and I've only just begun scratching the surface of the other one. But signs do point to that conclusion yes.

**Comment by toddbluhm** [comment]
Thank you all!

Deprecation notice and link to official apache plugin added to README and description.
